"""Stable host launcher that executes one service from the active published source."""

from __future__ import annotations

import argparse
import asyncio
import hashlib
import importlib.util
import json
import os
import signal
import re
import shutil
import subprocess
import sys
import platform
import tempfile
import time
import urllib.error
import urllib.request
from pathlib import Path
from typing import Any, Mapping


RUNTIME = Path.home() / "Library" / "Application Support" / "XJ Multiuser"
ACTIVE_LOCK = Path(
    os.environ.get("XJ_RELEASE_LOCK", str(RUNTIME / "data" / "active-release.json"))
).expanduser().resolve()
PRIVATE_TERMS = RUNTIME / "private" / "本机私密扫描词.txt"
RUNTIME_IDENTITY = RUNTIME / "host-python.json"
HOST_SWITCH = RUNTIME / "data" / "host-switch.json"
HOST_RUNTIME_SWITCH = RUNTIME / "data" / "host-runtime-switch.json"
LEGACY_PLIST = Path.home() / "Library" / "LaunchAgents" / "com.xj.multiuser.supervisor.plist"
FALLBACK_LABEL = "com.xj.multiuser.formal-fallback"
FALLBACK_PLIST = Path.home() / "Library" / "LaunchAgents" / f"{FALLBACK_LABEL}.plist"
DEVELOPMENT_ADMIN_PORT = 37660
DEVELOPMENT_ADMIN_STATUS_FILE = RUNTIME / "status" / "development-admin.json"
ROLE_LABELS = {
    "control": "com.xj.multiuser.control",
    "admin": "com.xj.multiuser.admin",
    "rerank": "com.xj.multiuser.rerank",
}
ROLE_PLISTS = {
    role: Path.home() / "Library" / "LaunchAgents" / f"{label}.plist"
    for role, label in ROLE_LABELS.items()
}
ROLE_SETTINGS: dict[str, tuple[str, str, int]] = {
    "control": ("XJ_SUPERVISOR_HOST", "XJ_SUPERVISOR_PORT", 37654),
    "admin": ("XJ_SUPERVISOR_HOST", "XJ_ADMIN_PORT", 37655),
    "rerank": ("XJ_RERANK_HOST", "XJ_RERANK_PORT", 37657),
}
ROLE_APPLICATIONS = {
    "control": "多用户.控制面.服务:app",
    "admin": "多用户.控制面.管理服务:app",
    "rerank": "多用户.控制面.本地精排服务:app",
}
_宿主切换终态 = frozenset({"failed", "completed", "aborted", "cancelled"})
# Formal release directory/version identities are deliberately lowercase.
# Candidate IDs are a separate identity: their UTC timestamp uses the fixed
# uppercase ``T``/``Z`` form generated by 发布仓库.  Keep the two validators
# separate so a candidate can be shadow-tested without weakening formal
# release validation.
_VERSION = re.compile(r"[a-z0-9][a-z0-9._-]{0,63}")
_CANDIDATE_VERSION = re.compile(r"candidate-[0-9]{8}T[0-9]{6}Z-[0-9a-f]{8}")
_SHA256 = re.compile(r"[0-9a-f]{64}")


class 宿主启动错误(RuntimeError):
    pass


def _核对唯一开发源(source: Path) -> Path:
    """启动器是独立副本，因此在这里再独立核对一次登记。"""
    source = source.expanduser().resolve()
    record = _读JSON(RUNTIME / "data" / "development-source.json")
    marker = _读JSON(source / ".xj-development-source.json")
    if (
        record.get("schema") != 2
        or Path(str(record.get("source") or "")).expanduser().resolve() != source
        or marker.get("schema") != 1
        or marker.get("kind") != "xiaojiu-canonical-development-source"
        or marker.get("source_id") != record.get("source_id")
        or marker.get("canonical_branch") != record.get("canonical_branch")
    ):
        raise 宿主启动错误("开发管理后台与本机唯一开发源登记不一致")
    result = subprocess.run(
        ["git", "-C", str(source), "branch", "--show-current"],
        stdin=subprocess.DEVNULL, text=True, capture_output=True, check=False,
    )
    if result.returncode != 0 or result.stdout.strip() != record.get("canonical_branch"):
        raise 宿主启动错误("开发管理后台没有运行在唯一开发线")
    store_text = os.environ.get("XJ_RELEASE_STORE", "").strip()
    if store_text:
        store = Path(store_text).expanduser().resolve()
        if source == store or store in source.parents:
            raise 宿主启动错误("封存或候选副本不能启动开发管理后台")
    return source


def 核对三角色入口(source: Path | str) -> dict[str, Any]:
    """静态核对候选源码是否具备三个正式宿主入口。

    这里只检查文件布局，不导入候选源码，也不触碰活动版本、账号或启动项。
    首轮宿主引导必须针对已经固定的候选副本做这项检查，不能拿开发目录代替。
    """
    root = Path(source).expanduser().resolve()
    missing: list[str] = []
    roles: dict[str, dict[str, Any]] = {}
    root_valid = root.is_dir() and not root.is_symlink()
    for role, application in ROLE_APPLICATIONS.items():
        module = application.partition(":")[0]
        path = root.joinpath(*module.split(".")).with_suffix(".py")
        resolved = path.resolve() if path.exists() else path
        present = bool(
            root_valid
            and path.is_file()
            and not path.is_symlink()
            and (resolved == root or root in resolved.parents)
        )
        roles[role] = {
            "module": module,
            "path": str(path),
            "present": present,
        }
        if not present:
            missing.append(role)
    return {
        "ready": root_valid and not missing,
        "source": str(root),
        "roles": roles,
        "missing": missing,
    }


def _正式角色列表(source: Path | str) -> tuple[str, ...]:
    """List host roles present in a sealed source tree.

    Older sealed releases predate optional host components such as local
    rerank. Recovery starts only the roles that release actually contains;
    new candidates still use the strict three-role check above.
    """
    root = Path(source).expanduser().resolve()
    roles: list[str] = []
    for role, application in ROLE_APPLICATIONS.items():
        module = application.partition(":")[0]
        path = root.joinpath(*module.split(".")).with_suffix(".py")
        if path.is_file() and not path.is_symlink() and (path == root or root in path.parents):
            roles.append(role)
    if not {"control", "admin"}.issubset(roles):
        raise 宿主启动错误("封存正式版本缺少控制或管理宿主入口")
    return tuple(roles)


def _读JSON(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise 宿主启动错误(f"活动版本指针无法读取：{path}") from exc
    if not isinstance(value, dict):
        raise 宿主启动错误("活动版本指针格式无效")
    return value


def _写JSON(path: Path, value: Mapping[str, Any]) -> dict[str, Any]:
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    payload = dict(value)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, ensure_ascii=False, sort_keys=True)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        path.chmod(0o600)
    finally:
        Path(temporary).unlink(missing_ok=True)
    return payload


def _树指纹(root: Path) -> dict[str, Any]:
    if not root.is_dir() or root.is_symlink():
        raise 宿主启动错误("正式版本源码目录不存在或不是普通目录")
    digest = hashlib.sha256()
    count = 0
    total_size = 0
    for path in sorted(root.rglob("*"), key=lambda item: item.relative_to(root).as_posix()):
        relative = path.relative_to(root)
        if path.is_symlink():
            raise 宿主启动错误(f"正式版本源码不允许符号链接：{relative}")
        if not path.is_file():
            continue
        content = path.read_bytes()
        digest.update(relative.as_posix().encode("utf-8") + b"\0")
        digest.update(b"x" if path.stat().st_mode & 0o111 else b"-")
        digest.update(len(content).to_bytes(8, "big"))
        digest.update(content)
        count += 1
        total_size += len(content)
    return {"sha256": digest.hexdigest(), "files": count, "bytes": total_size}


def _读取清单发布(
    release_path: Path,
    *,
    version: str,
    source_sha256: str,
    allow_staged: bool,
) -> dict[str, Any]:
    raw_release_path = release_path.expanduser()
    if raw_release_path.is_symlink():
        raise 宿主启动错误("活动版本没有指向受控的正式副本")
    try:
        release_path = raw_release_path.resolve(strict=True)
    except OSError as exc:
        raise 宿主启动错误("活动版本的正式副本不存在") from exc
    allowed_parent = {"published", "staged"} if allow_staged else {"published"}
    if (
        not release_path.is_dir()
        or release_path.is_symlink()
        or release_path.name != version
        or release_path.parent.name not in allowed_parent
    ):
        raise 宿主启动错误("活动版本没有指向受控的正式副本")
    manifest = _读JSON(release_path / "manifest.json")
    manifest_source = manifest.get("source") if isinstance(manifest.get("source"), dict) else {}
    manifest_sha = str(manifest_source.get("sha256") or "")
    if (
        manifest.get("version") != version
        or not _SHA256.fullmatch(source_sha256)
        or manifest_sha != source_sha256
    ):
        raise 宿主启动错误("活动版本与正式副本身份不一致")
    source = release_path / "source"
    actual = _树指纹(source)
    if any(actual[key] != manifest_source.get(key) for key in ("sha256", "files", "bytes")):
        raise 宿主启动错误("正式版本源码完整性校验失败，拒绝启动")
    return {
        "version": version,
        "version_name": str(manifest.get("version_name") or version),
        "release_path": str(release_path),
        "source_path": str(source.resolve()),
        "source_sha256": source_sha256,
        "manifest": manifest,
    }


def 解析活动发布(
    active_path: Path = ACTIVE_LOCK,
    *,
    legacy_path: Path | None = None,
) -> dict[str, Any]:
    path = active_path.expanduser().resolve()
    if not path.is_file() and legacy_path is not None and legacy_path.expanduser().is_file():
        path = legacy_path.expanduser().resolve()
    pointer = _读JSON(path)
    version = str(pointer.get("version") or "")
    source = pointer.get("source") if isinstance(pointer.get("source"), dict) else {}
    source_sha256 = str(source.get("sha256") or "")
    if pointer.get("schema") != 3 or not _VERSION.fullmatch(version):
        raise 宿主启动错误("活动版本指针身份无效")
    result = _读取清单发布(
        Path(str(pointer.get("release_path") or "")),
        version=version,
        source_sha256=source_sha256,
        allow_staged=False,
    )
    return {**result, "active_path": str(path)}


def 解析指定发布(
    release_path: Path,
    *,
    version: str,
    source_sha256: str,
    allow_staged: bool = False,
) -> dict[str, Any]:
    if not _VERSION.fullmatch(str(version or "")):
        raise 宿主启动错误("指定宿主版本号无效")
    return _读取清单发布(
        release_path,
        version=version,
        source_sha256=source_sha256,
        allow_staged=allow_staged,
    )


def 解析指定源码(
    source_path: Path,
    *,
    version: str,
    source_sha256: str,
    active_path: Path = ACTIVE_LOCK,
) -> dict[str, Any]:
    """解析固定候选源码供影子验收，绝不改变活动版本指针。"""
    if (
        not _CANDIDATE_VERSION.fullmatch(str(version or ""))
        or not _SHA256.fullmatch(str(source_sha256 or ""))
    ):
        raise 宿主启动错误("影子候选编号或源码指纹无效")
    source = source_path.expanduser().resolve()
    actual = _树指纹(source)
    if actual["sha256"] != source_sha256:
        raise 宿主启动错误("影子候选源码完整性校验失败")
    return {
        "version": version,
        "version_name": version,
        "release_path": str(source.parent),
        "source_path": str(source),
        "source_sha256": source_sha256,
        "active_path": str(active_path.expanduser().resolve()),
        "manifest": {},
    }


def _钥匙串(name: str) -> str:
    result = subprocess.run(
        [
            "/usr/bin/security", "find-generic-password",
            "-s", "xj-multiuser-platform", "-a", name, "-w",
        ],
        stdin=subprocess.DEVNULL,
        text=True,
        capture_output=True,
        check=False,
        timeout=10,
    )
    value = result.stdout.rstrip("\n")
    if result.returncode != 0 or not value or len(value) > 4096 or any(ord(char) < 32 for char in value):
        raise 宿主启动错误(f"宿主启动所需钥匙串配置不可用：{name}")
    return value


def _docker路径() -> str:
    configured = os.environ.get("XJ_DOCKER_BIN", "").strip()
    candidates = (
        Path(configured) if configured else None,
        Path("/opt/homebrew/bin/docker"),
        Path("/usr/local/bin/docker"),
        Path("/Applications/Docker.app/Contents/Resources/bin/docker"),
    )
    for path in candidates:
        if path is not None and path.is_file() and os.access(path, os.X_OK):
            return str(path.resolve())
    found = shutil.which("docker")
    if found:
        return str(Path(found).resolve())
    raise 宿主启动错误("找不到 Docker CLI")


def _冻结摘要() -> str:
    result = subprocess.run(
        [sys.executable, "-m", "pip", "freeze", "--all"],
        stdin=subprocess.DEVNULL,
        text=True,
        capture_output=True,
        check=False,
        timeout=30,
    )
    if result.returncode != 0:
        raise 宿主启动错误("无法核对宿主 Python 依赖")
    lines = sorted(line.strip() for line in result.stdout.splitlines() if line.strip())
    return hashlib.sha256(("\n".join(lines) + "\n").encode("utf-8")).hexdigest()


def 当前运行环境身份() -> dict[str, str | int]:
    return {
        "schema": 1,
        "python_executable": str(Path(sys.executable).resolve()),
        "python_version": platform.python_version(),
        "pip_freeze_sha256": _冻结摘要(),
    }


def 核对运行环境身份(path: Path = RUNTIME_IDENTITY) -> dict[str, str | int]:
    expected = _读JSON(path)
    actual = 当前运行环境身份()
    if any(expected.get(key) != value for key, value in actual.items()):
        raise 宿主启动错误("宿主 Python 运行环境与登记身份不一致")
    return actual


def 构建正式环境(
    role: str,
    release: Mapping[str, Any],
    *,
    port: int | None = None,
    inherited: Mapping[str, str] | None = None,
) -> dict[str, str]:
    if role not in ROLE_SETTINGS:
        raise 宿主启动错误("宿主服务角色无效")
    host_name, port_name, default_port = ROLE_SETTINGS[role]
    selected_port = default_port if port is None else int(port)
    if not 1024 <= selected_port <= 65535:
        raise 宿主启动错误("宿主服务端口无效")
    inherited_values = dict(inherited or os.environ)
    private_terms = Path(
        inherited_values.get("XJ_PRIVATE_TERMS_FILE", str(PRIVATE_TERMS))
    ).expanduser().resolve()
    if role != "rerank" and (not private_terms.is_file() or private_terms.is_symlink()):
        raise 宿主启动错误(f"缺少独立运行目录中的私密扫描词：{private_terms}")

    runtime_identity = 核对运行环境身份(
        Path(inherited_values.get("XJ_HOST_RUNTIME_MANIFEST", str(RUNTIME_IDENTITY)))
    )
    env = inherited_values
    env.pop("PYTHONHOME", None)
    source = str(Path(str(release["source_path"])).resolve())
    version = str(release["version"])
    shadow_text = inherited_values.get("XJ_HOST_SHADOW_ROOT", "").strip()
    shadow_root = Path(shadow_text).expanduser().resolve() if shadow_text else None
    if shadow_root is not None:
        allowed_shadow_parent = (RUNTIME / "shadow").resolve()
        if allowed_shadow_parent not in shadow_root.parents:
            raise 宿主启动错误("影子验收目录不在受控运行区")
        shadow_root.mkdir(parents=True, exist_ok=True, mode=0o700)
    data_root = shadow_root if shadow_root is not None else RUNTIME
    env.update({
        "PATH": os.pathsep.join((
            str(Path(sys.executable).resolve().parent),
            "/opt/homebrew/bin", "/usr/local/bin", "/usr/bin", "/bin",
            "/usr/sbin", "/sbin", "/Applications/Docker.app/Contents/Resources/bin",
        )),
        "PYTHONPATH": source,
        "PYTHONNOUSERSITE": "1",
        "PYTHONDONTWRITEBYTECODE": "1",
        "PYTHONUNBUFFERED": "1",
        "XJ_ACTIVE_VERSION": version,
        "XJ_RELEASE_SOURCE": source,
        "XJ_RELEASE_SOURCE_SHA256": str(release["source_sha256"]),
        "XJ_RELEASE_LOCK": str(Path(str(
            release.get("active_path")
            or inherited_values.get("XJ_RELEASE_LOCK")
            or ACTIVE_LOCK
        )).expanduser().resolve()),
        "XJ_HOST_ROLE": role,
        "XJ_HOST_PYTHON_VERSION": str(runtime_identity["python_version"]),
        "XJ_HOST_DEPENDENCY_SHA256": str(runtime_identity["pip_freeze_sha256"]),
        "XJ_HOST_STATUS_FILE": inherited_values.get(
            "XJ_HOST_STATUS_FILE", str(RUNTIME / "status" / f"{role}.json")
        ),
        "XJ_HOST_PYTHON": str(Path(sys.executable).resolve()),
        "XJ_REGISTRY_PATH": str(data_root / "data" / "registry.sqlite3"),
        "XJ_INSTANCE_DIR": str(data_root / "instance"),
        "XJ_POLICY_DIR": str(data_root / "policy"),
        "XJ_PRIVATE_TERMS_FILE": str(private_terms),
        "XJ_COMPANY_IMAGE": f"xj-company:{version}",
        "XJ_RUNNER_IMAGE": f"xj-runner:{version}",
        "XJ_SUPERVISOR_HOST": "127.0.0.1",
        "XJ_SUPERVISOR_PORT": "37654",
        "XJ_ADMIN_PORT": "37655",
        "XJ_RERANK_HOST": "127.0.0.1",
        "XJ_RERANK_PORT": "37657",
        host_name: "127.0.0.1",
        port_name: str(selected_port),
        "XJ_SUPERVISOR_TOKEN": _钥匙串("supervisor-token"),
        "XJ_RERANK_TOKEN": _钥匙串("rerank-token"),
        "XJ_PUBLIC_URL": _钥匙串("public-url").rstrip("/"),
        "XJ_DOCKER_BIN": _docker路径(),
    })
    # The rerank host process is also the single macOS owner of the alert
    # expression model.  It must never route its own request back through the
    # container bridge.
    if role == "rerank":
        env["XJ_ALERT_RENDER_LOCAL"] = "1"
        env.pop("XJ_ALERT_RENDER_REQUIRED", None)
        env.pop("XJ_ALERT_RENDER_URL", None)
        env.pop("XJ_ALERT_RENDER_TOKEN", None)
    if shadow_root is not None:
        env["XJ_HOST_SHADOW"] = "1"
    if role != "admin" or inherited_values.get("XJ_DEVELOPMENT_ADMIN") != "1":
        # Formal role hosts run only the sealed release.  The development
        # source belongs exclusively to the owner's separate admin process.
        env.pop("XJ_DEVELOPMENT_SOURCE", None)
    else:
        development = Path(env.get("XJ_DEVELOPMENT_SOURCE", "")).expanduser().resolve()
        if not development.is_dir():
            raise 宿主启动错误("管理服务缺少明确的开发源目录")
        env["XJ_DEVELOPMENT_SOURCE"] = str(development)
    return env


def _写角色状态(value: dict[str, Any]) -> None:
    text = os.environ.get("XJ_HOST_STATUS_FILE", "").strip()
    if not text:
        return
    path = Path(text).expanduser().resolve()
    path.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(
                {**value, "pid": os.getpid(), "updated_at": time.time()},
                handle,
                ensure_ascii=False,
                sort_keys=True,
            )
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    finally:
        Path(temporary).unlink(missing_ok=True)


def _切换状态(switch_id: str, **changes: Any) -> dict[str, Any]:
    state = _读JSON(HOST_SWITCH)
    if state.get("schema") != 1 or state.get("switch_id") != switch_id:
        raise 宿主启动错误("宿主切换记录已变化，拒绝继续")
    next_status = changes.get("status")
    if (
        next_status in {"switching", "host-ready"}
        and state.get("status") not in {"queued", "switching"}
    ):
        raise 宿主启动错误("宿主切换已被管理端终止，助手停止继续")
    state.update(changes)
    state["updated_at"] = time.time()
    return _写JSON(HOST_SWITCH, state)


def _核对切换仍有效(
    switch_id: str,
    *,
    allowed_statuses: frozenset[str] = frozenset({"queued", "switching"}),
) -> dict[str, Any]:
    """Fence a detached helper after management-side recovery or cancellation."""
    state = _读JSON(HOST_SWITCH)
    if state.get("schema") != 1 or state.get("switch_id") != switch_id:
        raise 宿主启动错误("宿主切换记录已变化，助手停止继续")
    status = state.get("status")
    if status not in allowed_statuses:
        if status == "failed":
            raise 宿主启动错误("宿主切换已被管理端终止，助手停止继续")
        raise 宿主启动错误(f"宿主切换状态不可继续：{status or '未知'}")
    return state


def _旧助手应退出(switch_id: str) -> bool:
    """Avoid tearing down a runtime that a newer or finished switch owns."""
    try:
        state = _读JSON(HOST_SWITCH)
    except BaseException:
        # Ownership cannot be established while the receipt is unreadable.
        # Failing closed is safer than stopping a runtime that may belong to a
        # newer helper; the management process can reconcile the stale switch
        # on its next recovery pass.
        return True
    if state.get("schema") != 1:
        return True
    return (
        state.get("switch_id") != switch_id
        or state.get("status") in {"completed", "aborted", "cancelled"}
    )


def _等待管理端收口(switch_id: str, *, timeout: float = 180) -> None:
    """Keep the candidate host alive until management commits or cancels it."""
    deadline = time.monotonic() + timeout
    last_stage = "管理端尚未收口"
    while time.monotonic() < deadline:
        state = _读JSON(HOST_SWITCH)
        if state.get("schema") != 1 or state.get("switch_id") != switch_id:
            raise 宿主启动错误("宿主切换记录已变化，助手停止继续")
        status = str(state.get("status") or "")
        if status == "completed":
            return
        if status == "failed":
            raise 宿主启动错误(str(state.get("error") or "管理端取消了宿主切换"))
        if status != "host-ready":
            raise 宿主启动错误(f"宿主切换状态不可收口：{status or '未知'}")
        last_stage = str(state.get("stage") or last_stage)
        time.sleep(0.25)
    raise 宿主启动错误(f"管理端在 {int(timeout)} 秒内没有收口：{last_stage}")


def _角色身份(role: str) -> dict[str, Any] | None:
    path = RUNTIME / "status" / f"{role}.json"
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return None
    return value if isinstance(value, dict) else None


def _健康请求(role: str) -> bool:
    port = ROLE_SETTINGS[role][2]
    request = urllib.request.Request(f"http://127.0.0.1:{port}/healthz")
    if role == "rerank":
        request.add_header("authorization", f"Bearer {_钥匙串('rerank-token')}")
    try:
        with urllib.request.urlopen(request, timeout=8) as response:
            return response.status == 200
    except (OSError, urllib.error.URLError):
        return False


def _等待角色(
    role: str,
    *,
    version: str,
    source_sha256: str,
    started_at: float,
    switch_id: str | None = None,
) -> None:
    deadline = time.monotonic() + (240 if role == "rerank" else 90)
    while time.monotonic() < deadline:
        if switch_id:
            _核对切换仍有效(switch_id)
        identity = _角色身份(role)
        if (
            identity is not None
            and identity.get("status") == "running"
            and identity.get("role") == role
            and identity.get("version") == version
            and identity.get("source_sha256") == source_sha256
            and float(identity.get("updated_at") or 0) >= started_at
            and _健康请求(role)
        ):
            if switch_id:
                _核对切换仍有效(switch_id)
            return
        time.sleep(0.25)
    raise 宿主启动错误(f"{role} 没有在限时内运行目标正式版本")


def _launchctl(*args: str, check: bool = True) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["/bin/launchctl", *args],
        stdin=subprocess.DEVNULL,
        text=True,
        capture_output=True,
        check=check,
        timeout=45,
    )


def _恢复暂存宿主运行面(switch_id: str) -> None:
    try:
        state = _读JSON(HOST_RUNTIME_SWITCH)
    except Exception:
        return
    if state.get("schema") != 1 or state.get("switch_id") != switch_id:
        return
    backup = Path(str(state.get("backup_dir") or "")).expanduser().resolve()
    allowed = (RUNTIME / "data" / "host-runtime-backups").resolve()
    if allowed not in backup.parents or not backup.is_dir():
        return
    paths = {**ROLE_PLISTS, "fallback": FALLBACK_PLIST}
    restore_errors: list[str] = []
    for role, path in paths.items():
        source = backup / f"{role}.plist"
        try:
            if source.stat().st_size:
                shutil.copy2(source, path)
            else:
                path.unlink(missing_ok=True)
        except OSError as exc:
            restore_errors.append(f"{role}:{type(exc).__name__}")
    # The release lock was already advanced before the helper started.  Put
    # the exact pre-switch pointer back before loading the frozen fallback;
    # otherwise the old plist would run while reporting the new version.
    active_source = backup / "active-release.json"
    try:
        if active_source.is_file() and active_source.stat().st_size:
            if ACTIVE_LOCK.is_symlink():
                raise OSError("活动版本指针是符号链接")
            temporary = ACTIVE_LOCK.with_name(
                f".{ACTIVE_LOCK.name}.{os.getpid()}.restore"
            )
            try:
                shutil.copy2(active_source, temporary)
                os.replace(temporary, ACTIVE_LOCK)
            finally:
                temporary.unlink(missing_ok=True)
        elif active_source.is_file():
            ACTIVE_LOCK.unlink(missing_ok=True)
    except OSError as exc:
        restore_errors.append(f"active-lock:{type(exc).__name__}")
    if restore_errors:
        _写JSON(HOST_RUNTIME_SWITCH, {
            **state,
            "status": "restore-failed",
            "restore_errors": restore_errors,
            "restored_at": time.time(),
        })
        raise 宿主启动错误("宿主旧运行面恢复失败：" + "、".join(restore_errors))
    _写JSON(HOST_RUNTIME_SWITCH, {**state, "status": "restored", "restored_at": time.time()})


def _退回未完成正式副本(state: Mapping[str, Any]) -> str:
    """失败回退时先把未完成版本移出 published，避免旧后台误读。"""
    target = state.get("target") if isinstance(state.get("target"), Mapping) else {}
    version = str(target.get("version") or "")
    source_sha256 = str(target.get("source_sha256") or "")
    raw_path = str(target.get("release_path") or "")
    if not _VERSION.fullmatch(version) or not _SHA256.fullmatch(source_sha256) or not raw_path:
        raise 宿主启动错误("失败切换缺少可核对的正式副本身份")
    published = Path(raw_path).expanduser().resolve()
    if published.name != version or published.parent.name != "published":
        raise 宿主启动错误("失败切换的正式副本路径无效")
    staged = published.parent.parent / "staged" / version
    if not published.exists():
        if staged.is_dir():
            return "未完成正式副本已退回预发布区"
        return "未完成正式副本不存在"
    if not published.is_dir() or published.is_symlink() or staged.exists():
        raise 宿主启动错误("未完成正式副本无法安全退回预发布区")
    manifest = _读JSON(published / "manifest.json")
    source = manifest.get("source") if isinstance(manifest.get("source"), Mapping) else {}
    if manifest.get("version") != version or source.get("sha256") != source_sha256:
        raise 宿主启动错误("未完成正式副本身份与宿主切换目标不一致")
    try:
        active = 解析活动发布(ACTIVE_LOCK)
    except 宿主启动错误:
        active = {}
    if active.get("version") == version:
        raise 宿主启动错误("活动版本仍指向失败目标，不能移动正式副本")
    staged.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    published.rename(staged)
    return "未完成正式副本已退回预发布区"


def _确认暂存宿主运行面(switch_id: str) -> None:
    _核对切换仍有效(
        switch_id,
        allowed_statuses=frozenset({"switching", "host-ready"}),
    )
    try:
        state = _读JSON(HOST_RUNTIME_SWITCH)
    except Exception:
        return
    if state.get("schema") == 1 and state.get("switch_id") == switch_id:
        # The three host processes are ready, but the platform, accounts and
        # final release receipt may still be pending.  Keep that distinction
        # explicit so only the management closeout can mark this transaction
        # as the stable baseline for a later release.
        _写JSON(HOST_RUNTIME_SWITCH, {
            **state,
            "status": "host-ready",
            "host_ready_at": time.time(),
        })


def _启动新角色(role: str, *, migration: bool) -> float:
    domain = f"gui/{os.getuid()}"
    status = RUNTIME / "status" / f"{role}.json"
    status.unlink(missing_ok=True)
    started_at = time.time()
    # A prior failed migration may have left the sealed single-process
    # fallback loaded.  Unload it before binding any of the three ports.
    # The plist remains on disk as the emergency recovery description.
    _launchctl("bootout", domain, str(FALLBACK_PLIST), check=False)
    plist = ROLE_PLISTS[role]
    if not plist.is_file() or plist.is_symlink():
        raise 宿主启动错误(f"{role} 的正式启动描述尚未准备")
    # 暂存候选时磁盘上的 plist 已替换为候选运行环境。无论这是首次迁移
    # 还是后续发布，都必须重新 bootstrap（让 macOS 重新读取启动文件）。
    # 只 kickstart 会继续使用 launchd 内存里的旧配置；任务尚未加载时还会
    # 直接返回 113。
    _launchctl("bootout", domain, str(plist), check=False)
    try:
        _launchctl("bootstrap", domain, str(plist))
    except subprocess.CalledProcessError as exc:
        detail = str(exc.stderr or exc.stdout or "").strip().replace("\n", " ")[:240]
        suffix = f"：{detail}" if detail else ""
        raise 宿主启动错误(f"{role} 的正式服务没有加载成功{suffix}") from exc
    return started_at


def _恢复冻结正式单进程(
    started_roles: list[str], *, version: str, source_sha256: str,
) -> str:
    domain = f"gui/{os.getuid()}"
    failures: list[str] = []
    # Stop every role description, not only roles recorded as started.  A
    # launchctl/bootstrap failure can happen after a process has bound its
    # port but before the helper records it; leaving that process alive would
    # make the fallback fail with an address-in-use error.
    for role in reversed(tuple(ROLE_PLISTS)):
        try:
            _launchctl("bootout", domain, str(ROLE_PLISTS[role]), check=False)
        except Exception as exc:
            failures.append(f"{role} 停止失败：{type(exc).__name__}")
    if not FALLBACK_PLIST.is_file() or FALLBACK_PLIST.is_symlink():
        failures.append("冻结正式单进程启动项不存在")
    else:
        try:
            active = 解析活动发布(ACTIVE_LOCK)
            roles = _正式角色列表(Path(str(active["source_path"])))
            for role in ROLE_SETTINGS:
                (RUNTIME / "status" / f"{role}.json").unlink(missing_ok=True)
            started_at = time.time()
            _launchctl("bootout", domain, str(FALLBACK_PLIST), check=False)
            _launchctl("bootstrap", domain, str(FALLBACK_PLIST))
            for role in roles:
                _等待角色(
                    role,
                    version=version,
                    source_sha256=source_sha256,
                    started_at=started_at,
                )
        except Exception as exc:
            detail = str(exc).strip() or type(exc).__name__
            failures.append(f"冻结正式单进程恢复失败：{detail[:240]}")
    return "已从激活的冻结正式副本恢复三端口" if not failures else "；".join(failures)


def 恢复活动冻结正式后台() -> dict[str, Any]:
    """从当前活动的封存版本恢复正式后台，并确认该版本拥有的入口全部在线。"""
    active = 解析活动发布(ACTIVE_LOCK)
    version = str(active["version"])
    source_sha256 = str(active["source_sha256"])
    roles = _正式角色列表(Path(str(active["source_path"])))
    result = _恢复冻结正式单进程(
        [], version=version, source_sha256=source_sha256,
    )
    if result != "已从激活的冻结正式副本恢复三端口":
        raise 宿主启动错误(result)
    return {
        "status": "restored",
        "mode": "formal-fallback",
        "version": version,
        "source_sha256": source_sha256,
        "roles": list(roles),
    }


def 恢复活动正式后台() -> dict[str, Any]:
    """从活动封存版恢复独立宿主；失败时只把备用进程作为应急保障。"""
    active = 解析活动发布(ACTIVE_LOCK)
    version = str(active["version"])
    source_sha256 = str(active["source_sha256"])
    available = set(_正式角色列表(Path(str(active["source_path"]))))
    roles = tuple(role for role in ("control", "rerank", "admin") if role in available)
    started_roles: list[str] = []
    try:
        for role in roles:
            started_at = _启动新角色(role, migration=False)
            started_roles.append(role)
            _等待角色(
                role,
                version=version,
                source_sha256=source_sha256,
                started_at=started_at,
            )
    except BaseException as exc:
        fallback = _恢复冻结正式单进程(
            started_roles,
            version=version,
            source_sha256=source_sha256,
        )
        detail = str(exc).strip() or type(exc).__name__
        raise 宿主启动错误(
            f"三个独立正式宿主恢复失败：{detail[:240]}；{fallback}"
        ) from exc
    return {
        "status": "restored",
        "mode": "formal",
        "version": version,
        "source_sha256": source_sha256,
        "roles": list(roles),
    }


def 执行宿主切换(switch_id: str) -> None:
    """Run outside managed services; replace admin last and leave durable evidence."""
    state = _读JSON(HOST_SWITCH)
    if state.get("schema") != 1 or state.get("switch_id") != switch_id:
        raise 宿主启动错误("宿主切换记录不匹配")
    target = state.get("target") if isinstance(state.get("target"), dict) else {}
    version = str(target.get("version") or "")
    source_sha256 = str(target.get("source_sha256") or "")
    migration = state.get("mode") == "legacy-migration"
    started_roles: list[str] = []
    try:
        _核对切换仍有效(switch_id)
        _切换状态(
            switch_id,
            status="switching",
            stage="正在切换公司控制和本地精排",
            started_at=state.get("started_at") or time.time(),
            error="",
        )
        # The active pointer can change while the management process is
        # restarting.  Keep this validation inside the recovery boundary so a
        # mismatch still restores the exact pre-switch host snapshot.
        active = 解析活动发布(ACTIVE_LOCK)
        if active["version"] != version or active["source_sha256"] != source_sha256:
            raise 宿主启动错误("活动版本与宿主切换目标不一致")
        if migration:
            if not LEGACY_PLIST.is_file() or LEGACY_PLIST.is_symlink():
                raise 宿主启动错误("旧单进程启动项不存在，无法安全迁移")
            _launchctl("bootout", f"gui/{os.getuid()}", str(LEGACY_PLIST), check=False)
        for role in ("control", "rerank"):
            _核对切换仍有效(switch_id)
            started_at = _启动新角色(role, migration=migration)
            started_roles.append(role)
            _核对切换仍有效(switch_id)
            _等待角色(
                role,
                version=version,
                source_sha256=source_sha256,
                started_at=started_at,
                switch_id=switch_id,
            )
        _核对切换仍有效(switch_id)
        _切换状态(
            switch_id,
            status="switching",
            stage="控制和精排已健康，正在最后更换管理后台",
        )
        _核对切换仍有效(switch_id)
        started_at = _启动新角色("admin", migration=migration)
        started_roles.append("admin")
        _核对切换仍有效(switch_id)
        _等待角色(
            "admin",
            version=version,
            source_sha256=source_sha256,
            started_at=started_at,
            switch_id=switch_id,
        )
        _核对切换仍有效(switch_id)
        _切换状态(
            switch_id,
            status="host-ready",
            stage="三个宿主服务已运行目标正式版本，等待管理后台收口",
            host_ready_at=time.time(),
            fallback="",
        )
        _确认暂存宿主运行面(switch_id)
        # Do not exit while the shared platform and accounts are still being
        # switched.  If management reports a failure, this same helper owns
        # the process-level rollback and starts the sealed fallback.
        _等待管理端收口(switch_id)
    except BaseException as exc:
        # Management recovery or a newer switch may have taken ownership
        # while this detached helper was unwinding.  In either case, touching
        # launchd or starting the fallback here could tear down the new owner.
        if _旧助手应退出(switch_id):
            return
        # Restore the exact pre-switch pointer and launch descriptions before
        # the frozen fallback.  The fallback must never claim the new version
        # when the three-role switch did not become healthy.
        restore_error = ""
        try:
            _恢复暂存宿主运行面(switch_id)
        except BaseException as restore_exc:
            restore_error = f"；旧宿主运行面恢复失败：{str(restore_exc).strip() or type(restore_exc).__name__}"
        try:
            artifact_fallback = _退回未完成正式副本(state)
        except BaseException as artifact_exc:
            artifact_fallback = f"未完成正式副本退回失败：{str(artifact_exc).strip() or type(artifact_exc).__name__}"
            restore_error += f"；{artifact_fallback}"
        # Read the pointer *after* restoration.  Passing the failed target
        # here would make the fallback start old code while waiting for the
        # target identity (and could leave the machine in a false healthy
        # state).
        try:
            fallback_active = 解析活动发布(ACTIVE_LOCK)
            fallback = _恢复冻结正式单进程(
                started_roles,
                version=str(fallback_active["version"]),
                source_sha256=str(fallback_active["source_sha256"]),
            )
        except BaseException as fallback_exc:
            fallback = f"冻结正式单进程恢复失败：{str(fallback_exc).strip() or type(fallback_exc).__name__}"
        _切换状态(
            switch_id,
            status="failed",
            stage="宿主运行面切换失败",
            completed_at=time.time(),
            error=((str(exc).strip() or type(exc).__name__) + restore_error)[:500],
            fallback=fallback,
            artifact_fallback=artifact_fallback,
        )
        raise


def _正式模块路径(role: str, source: Path) -> Path:
    module_name = ROLE_APPLICATIONS[role].partition(":")[0]
    spec = importlib.util.find_spec(module_name)
    origin = Path(str(spec.origin or "")).resolve() if spec is not None else Path()
    if not origin.is_file() or source not in origin.parents:
        raise 宿主启动错误(f"{role} 没有从选定正式源码加载")
    return origin


async def _运行角色进程(role: str) -> None:
    if role not in ROLE_SETTINGS:
        raise 宿主启动错误("宿主服务角色无效")
    source = Path(os.environ.get("XJ_RELEASE_SOURCE", "")).expanduser().resolve()
    version = os.environ.get("XJ_ACTIVE_VERSION", "").strip()
    source_sha256 = os.environ.get("XJ_RELEASE_SOURCE_SHA256", "").strip()
    python_version = os.environ.get("XJ_HOST_PYTHON_VERSION", "").strip()
    dependency_sha256 = os.environ.get("XJ_HOST_DEPENDENCY_SHA256", "").strip()
    if (
        not source.is_dir() or not version or len(source_sha256) != 64
        or not python_version or len(dependency_sha256) != 64
    ):
        raise 宿主启动错误("宿主服务缺少正式运行身份")
    module = _正式模块路径(role, source)
    host_name, port_name, default_port = ROLE_SETTINGS[role]
    host = os.environ.get(host_name, "127.0.0.1")
    try:
        port = int(os.environ.get(port_name, str(default_port)))
    except ValueError as exc:
        raise 宿主启动错误("宿主服务端口无效") from exc
    if host != "127.0.0.1" or not 1024 <= port <= 65535:
        raise 宿主启动错误("宿主服务只允许监听本机高位端口")

    import uvicorn

    server = uvicorn.Server(uvicorn.Config(
        ROLE_APPLICATIONS[role],
        host=host,
        port=port,
        log_level="info",
        proxy_headers=False,
        forwarded_allow_ips="",
    ))
    server.install_signal_handlers = lambda: None
    loop = asyncio.get_running_loop()

    def stop() -> None:
        server.should_exit = True

    for sig in (signal.SIGINT, signal.SIGTERM):
        loop.add_signal_handler(sig, stop)
    base = {
        "role": role,
        "version": version,
        "source": str(source),
        "source_sha256": source_sha256,
        "module": str(module),
        "python_version": python_version,
        "dependency_sha256": dependency_sha256,
        "host": host,
        "port": port,
    }
    _写角色状态({**base, "status": "starting"})
    task = asyncio.create_task(server.serve())
    try:
        while not server.started and not task.done():
            await asyncio.sleep(0.05)
        if server.started:
            _写角色状态({**base, "status": "running"})
        await task
        _写角色状态({**base, "status": "stopped"})
    except BaseException as exc:
        _写角色状态({**base, "status": "failed", "error": type(exc).__name__})
        raise


async def _运行冻结正式单进程() -> None:
    """Emergency fallback using only roles available in the active sealed source."""
    source = Path(os.environ.get("XJ_RELEASE_SOURCE", "")).expanduser().resolve()
    version = os.environ.get("XJ_ACTIVE_VERSION", "").strip()
    source_sha256 = os.environ.get("XJ_RELEASE_SOURCE_SHA256", "").strip()
    python_version = os.environ.get("XJ_HOST_PYTHON_VERSION", "").strip()
    dependency_sha256 = os.environ.get("XJ_HOST_DEPENDENCY_SHA256", "").strip()
    if not source.is_dir() or not version or len(source_sha256) != 64:
        raise 宿主启动错误("冻结正式回退身份不完整")
    roles = _正式角色列表(source)
    modules = {role: _正式模块路径(role, source) for role in roles}
    import uvicorn

    servers = []
    bases: dict[str, dict[str, Any]] = {}
    for role in roles:
        _, _, port = ROLE_SETTINGS[role]
        server = uvicorn.Server(uvicorn.Config(
            ROLE_APPLICATIONS[role], host="127.0.0.1", port=port,
            log_level="info", proxy_headers=False, forwarded_allow_ips="",
        ))
        server.install_signal_handlers = lambda: None
        servers.append((role, server))
        bases[role] = {
            "role": role,
            "version": version,
            "source": str(source),
            "source_sha256": source_sha256,
            "module": str(modules[role]),
            "python_version": python_version,
            "dependency_sha256": dependency_sha256,
            "host": "127.0.0.1",
            "port": port,
            "fallback": "formal-single-process",
        }
    loop = asyncio.get_running_loop()

    def stop() -> None:
        for _, server in servers:
            server.should_exit = True

    for sig in (signal.SIGINT, signal.SIGTERM):
        loop.add_signal_handler(sig, stop)
    for role in bases:
        original = os.environ.get("XJ_HOST_STATUS_FILE")
        os.environ["XJ_HOST_STATUS_FILE"] = str(RUNTIME / "status" / f"{role}.json")
        _写角色状态({**bases[role], "status": "starting"})
        if original is None:
            os.environ.pop("XJ_HOST_STATUS_FILE", None)
        else:
            os.environ["XJ_HOST_STATUS_FILE"] = original
    tasks = {role: asyncio.create_task(server.serve()) for role, server in servers}
    try:
        while not all(server.started for _, server in servers) and not any(
            task.done() for task in tasks.values()
        ):
            await asyncio.sleep(0.05)
        if all(server.started for _, server in servers):
            for role in bases:
                original = os.environ.get("XJ_HOST_STATUS_FILE")
                os.environ["XJ_HOST_STATUS_FILE"] = str(RUNTIME / "status" / f"{role}.json")
                _写角色状态({**bases[role], "status": "running"})
                if original is None:
                    os.environ.pop("XJ_HOST_STATUS_FILE", None)
                else:
                    os.environ["XJ_HOST_STATUS_FILE"] = original
        await asyncio.gather(*tasks.values())
    finally:
        stop()


async def _运行开发管理后台() -> None:
    """Run the owner's development management UI on its private loopback port.

    The management code must follow the one development tree so that a new
    candidate is visible before it is published.  Its release APIs still use
    the active sealed version for accounts and runtime recovery; only the UI
    and release orchestration code come from the development source.
    """
    source = _核对唯一开发源(
        Path(os.environ.get("XJ_DEVELOPMENT_SOURCE", "")),
    )
    version = os.environ.get("XJ_ACTIVE_VERSION", "").strip()
    active_source = Path(os.environ.get("XJ_RELEASE_SOURCE", "")).expanduser().resolve()
    source_sha256 = os.environ.get("XJ_RELEASE_SOURCE_SHA256", "").strip()
    python_version = os.environ.get("XJ_HOST_PYTHON_VERSION", "").strip()
    dependency_sha256 = os.environ.get("XJ_HOST_DEPENDENCY_SHA256", "").strip()
    module = source / "多用户" / "控制面" / "管理服务.py"
    if (
        not source.is_dir() or source.is_symlink() or not module.is_file()
        or not active_source.is_dir() or not version or len(source_sha256) != 64
    ):
        raise 宿主启动错误("开发管理后台身份不完整")
    try:
        port = int(os.environ.get("XJ_ADMIN_PORT", str(DEVELOPMENT_ADMIN_PORT)))
    except ValueError as exc:
        raise 宿主启动错误("开发管理后台端口无效") from exc
    if not 1024 <= port <= 65535:
        raise 宿主启动错误("开发管理后台端口无效")

    import uvicorn

    server = uvicorn.Server(uvicorn.Config(
        "多用户.控制面.管理服务:app",
        host="127.0.0.1",
        port=port,
        log_level="info",
        proxy_headers=False,
        forwarded_allow_ips="",
    ))
    server.install_signal_handlers = lambda: None
    loop = asyncio.get_running_loop()

    def stop() -> None:
        server.should_exit = True

    for sig in (signal.SIGINT, signal.SIGTERM):
        loop.add_signal_handler(sig, stop)
    status_file = Path(
        os.environ.get("XJ_HOST_STATUS_FILE", str(DEVELOPMENT_ADMIN_STATUS_FILE))
    ).expanduser().resolve()
    base = {
        "role": "admin-development",
        "version": version,
        "source": str(source),
        "source_sha256": "development",
        "formal_source": str(active_source),
        "formal_source_sha256": source_sha256,
        "module": str(module),
        "python_version": python_version,
        "dependency_sha256": dependency_sha256,
        "host": "127.0.0.1",
        "port": port,
        "development_only": True,
    }
    original_status_file = os.environ.get("XJ_HOST_STATUS_FILE")
    os.environ["XJ_HOST_STATUS_FILE"] = str(status_file)
    _写角色状态({**base, "status": "starting"})
    if original_status_file is None:
        os.environ.pop("XJ_HOST_STATUS_FILE", None)
    else:
        os.environ["XJ_HOST_STATUS_FILE"] = original_status_file
    task = asyncio.create_task(server.serve())
    try:
        while not server.started and not task.done():
            await asyncio.sleep(0.05)
        if server.started:
            original_status_file = os.environ.get("XJ_HOST_STATUS_FILE")
            os.environ["XJ_HOST_STATUS_FILE"] = str(status_file)
            _写角色状态({**base, "status": "running"})
            if original_status_file is None:
                os.environ.pop("XJ_HOST_STATUS_FILE", None)
            else:
                os.environ["XJ_HOST_STATUS_FILE"] = original_status_file
        await task
        original_status_file = os.environ.get("XJ_HOST_STATUS_FILE")
        os.environ["XJ_HOST_STATUS_FILE"] = str(status_file)
        _写角色状态({**base, "status": "stopped"})
        if original_status_file is None:
            os.environ.pop("XJ_HOST_STATUS_FILE", None)
        else:
            os.environ["XJ_HOST_STATUS_FILE"] = original_status_file
    except BaseException as exc:
        original_status_file = os.environ.get("XJ_HOST_STATUS_FILE")
        os.environ["XJ_HOST_STATUS_FILE"] = str(status_file)
        _写角色状态({**base, "status": "failed", "error": type(exc).__name__})
        if original_status_file is None:
            os.environ.pop("XJ_HOST_STATUS_FILE", None)
        else:
            os.environ["XJ_HOST_STATUS_FILE"] = original_status_file
        raise


def 启动开发管理后台(
    *,
    active_path: Path = ACTIVE_LOCK,
    source_path: Path | None = None,
    port: int = DEVELOPMENT_ADMIN_PORT,
) -> None:
    """Start owner-only management code from the development tree."""
    release = 解析活动发布(active_path)
    source = (
        source_path
        or Path(os.environ.get("XJ_DEVELOPMENT_SOURCE", "")).expanduser()
    ).expanduser().resolve()
    source = _核对唯一开发源(source)
    if not source.is_dir() or source.is_symlink():
        raise 宿主启动错误("管理员开发目录不存在")
    if not (source / "多用户" / "控制面" / "管理服务.py").is_file():
        raise 宿主启动错误("管理员开发目录缺少管理服务")
    env = 构建正式环境("admin", release, port=port, inherited=os.environ.copy())
    env["PYTHONPATH"] = str(source)
    env["XJ_DEVELOPMENT_SOURCE"] = str(source)
    env["XJ_ADMIN_PORT"] = str(port)
    env["XJ_HOST_STATUS_FILE"] = str(
        Path(env.get("XJ_HOST_STATUS_FILE", str(DEVELOPMENT_ADMIN_STATUS_FILE)))
        .expanduser().resolve()
    )
    env["XJ_HOST_BOUNDARY_MODE"] = "development-admin"
    env["XJ_HOST_ROLE"] = "admin"
    env["XJ_DEVELOPMENT_ADMIN"] = "1"
    os.chdir(source)
    os.execve(
        sys.executable,
        [sys.executable, str(Path(__file__).resolve()), "run-development-admin"],
        env,
    )


def 启动角色(
    role: str,
    *,
    active_path: Path = ACTIVE_LOCK,
    legacy_path: Path | None = None,
    release_path: Path | None = None,
    source_path: Path | None = None,
    version: str = "",
    source_sha256: str = "",
    allow_staged: bool = False,
    port: int | None = None,
) -> None:
    if source_path is not None:
        release = 解析指定源码(
            source_path,
            version=version,
            source_sha256=source_sha256,
            active_path=active_path,
        )
    elif release_path is None:
        release = 解析活动发布(active_path, legacy_path=legacy_path)
    else:
        release = 解析指定发布(
            release_path,
            version=version,
            source_sha256=source_sha256,
            allow_staged=allow_staged,
        )
    env = 构建正式环境(role, release, port=port)
    source = Path(str(release["source_path"]))
    os.chdir(source)
    os.execve(
        sys.executable,
        [sys.executable, str(Path(__file__).resolve()), "run-child", "--role", role],
        env,
    )


def 启动冻结正式单进程(*, active_path: Path = ACTIVE_LOCK) -> None:
    release = 解析活动发布(active_path)
    env = 构建正式环境("admin", release)
    env["XJ_HOST_BOUNDARY_MODE"] = "formal-fallback"
    env.pop("XJ_HOST_ROLE", None)
    source = Path(str(release["source_path"]))
    os.chdir(source)
    os.execve(
        sys.executable,
        [sys.executable, str(Path(__file__).resolve()), "run-legacy-child"],
        env,
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "command", choices=(
            "serve", "serve-legacy", "serve-development-admin", "verify", "runtime-identity",
            "run-child", "run-legacy-child", "run-development-admin", "switch",
        )
    )
    parser.add_argument("--role", choices=tuple(ROLE_SETTINGS), default="control")
    parser.add_argument("--active-lock", type=Path, default=ACTIVE_LOCK)
    parser.add_argument("--legacy-lock", type=Path)
    parser.add_argument("--release-path", type=Path)
    parser.add_argument("--source-path", type=Path)
    parser.add_argument("--version", default="")
    parser.add_argument("--source-sha256", default="")
    parser.add_argument("--allow-staged", action="store_true")
    parser.add_argument("--port", type=int)
    parser.add_argument("--switch-id", default="")
    args = parser.parse_args()
    if args.command == "runtime-identity":
        print(json.dumps(当前运行环境身份(), ensure_ascii=False, sort_keys=True))
        return 0
    if args.command == "run-child":
        asyncio.run(_运行角色进程(args.role))
        return 0
    if args.command == "run-legacy-child":
        asyncio.run(_运行冻结正式单进程())
        return 0
    if args.command == "run-development-admin":
        asyncio.run(_运行开发管理后台())
        return 0
    if args.command == "switch":
        if not args.switch_id:
            parser.error("switch 需要 --switch-id")
        执行宿主切换(args.switch_id)
        return 0
    if args.command == "serve-legacy":
        启动冻结正式单进程(active_path=args.active_lock)
        return 0
    if args.command == "serve-development-admin":
        启动开发管理后台(
            active_path=args.active_lock,
            source_path=args.source_path,
            port=args.port or DEVELOPMENT_ADMIN_PORT,
        )
        return 0
    if args.source_path is not None:
        release = 解析指定源码(
            args.source_path,
            version=args.version,
            source_sha256=args.source_sha256,
            active_path=args.active_lock,
        )
    elif args.release_path is None:
        release = 解析活动发布(args.active_lock, legacy_path=args.legacy_lock)
    else:
        release = 解析指定发布(
            args.release_path,
            version=args.version,
            source_sha256=args.source_sha256,
            allow_staged=args.allow_staged,
        )
    if args.command == "verify":
        print(json.dumps({key: value for key, value in release.items() if key != "manifest"}, ensure_ascii=False))
        return 0
    启动角色(
        args.role,
        active_path=args.active_lock,
        legacy_path=args.legacy_lock,
        release_path=args.release_path,
        source_path=args.source_path,
        version=args.version,
        source_sha256=args.source_sha256,
        allow_staged=args.allow_staged,
        port=args.port,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
